name: AITranslator
version: 1.0
main: org.pytenix.SpigotTranslator
api-version: 1.20 # Oder deine Zielversion
author: PytenixOG
description: Übersetzt Chat-Pakete asynchron via OpenAI
folia-supported: true
depend: [packetevents]
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot